name: Auto-update dist

on:
  pull_request:
    branches: [main]
    paths:
      - dist/**

jobs:
  build:
    name: Update dist
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No build required"'
