name: Housekeeping
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    inputs:
      retain_days:
        type: string
        default: "0"
        description: "Minimum age of runs to keep"
        required: false
      min_num_runs:
        type: string
        default: "0"
        description: "Min number of runs to keep"
        required: false

jobs:
  clean-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        id: setup
        run: |
          if [[ ! -z "${{ github.event.inputs.retain_days }}" ]]; then
            echo "retain_days=${{ github.event.inputs.retain_days }}" >> $GITHUB_OUTPUT
          else
            echo "retain_days=1" >> $GITHUB_OUTPUT
          fi
          if [[ ! -z "${{ github.event.inputs.min_num_runs }}" ]]; then
            echo "min_runs=${{ github.event.inputs.min_num_runs }}" >> $GITHUB_OUTPUT
          else
            echo "min_runs=1" >> $GITHUB_OUTPUT
          fi

      - name: clean runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: ${{ steps.setup.outputs.retain_days }}
          keep_minimum_runs: ${{ steps.setup.outputs.min_runs }}
